esphome:
  name: test
  friendly_name: Test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret test_api_key

ota:
  password: !secret test_ota_password

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password

  fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

captive_portal:

